deployment:
  replicas: 1

# Enable the dashboard and API
api:
  dashboard: true
  insecure: true  # Insecure for local dev only

ingressRoute:
  dashboard:
    enabled: true

ports:
  web:
    port: 80
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose: false  # You can enable this for HTTPS later

service:
  type: LoadBalancer  # Works fine in Docker Desktop, becomes NodePort

logs:
  general:
    level: DEBUG

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true