admin:
  user: admin
  password: admin

service:
  type: ClusterIP

persistence:
  enabled: false

datasources:
  secretDefinition:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-kube-prometheus-prometheus.infra.svc.cluster.local:9090
          isDefault: true